version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "chmod +x ../entrypoint.sh && ../entrypoint.sh"
    environment:
      - DJANGO_SETTINGS_MODULE=covidtracker.settings.dev
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres-data:
