# Generated by Django 3.0.4 on 2020-04-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturecheck',
            name='check_date',
            field=models.DateTimeField(),
        ),
    ]
