# Generated by Django 3.0.4 on 2020-03-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('is_positive', models.BooleanField()),
            ],
        ),
    ]
