# Generated by Django 3.0.4 on 2020-03-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200331_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='detail',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
